### ISSUE TITLE
log dump for latest test

### ISSUE THREAD

**Issue by karimkohel** [RobEn-AAST/Discord-bot#10]
this is a dump of the latest test and should be worked on 

Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/karimkohel/Bo2loz/bo2loz_venv/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/karimkohel/Bo2loz/meetings.py", line 68, in on_voice_state_update
    members = voice_channel.members
AttributeError: 'NoneType' object has no attribute 'members'
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/karimkohel/Bo2loz/bo2loz_venv/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/karimkohel/Bo2loz/meetings.py", line 68, in on_voice_state_update
    members = voice_channel.members
AttributeError: 'NoneType' object has no attribute 'members'
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/karimkohel/Bo2loz/bo2loz_venv/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/karimkohel/Bo2loz/meetings.py", line 68, in on_voice_state_update
    members = voice_channel.members
AttributeError: 'NoneType' object has no attribute 'members'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/karimkohel/Bo2loz/bo2loz_venv/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "RobEn.py", line 70, in on_message
    if message.author.bot or message.channel.id != message.author.dm_channel.id:
AttributeError: 'NoneType' object has no attribute 'id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/karimkohel/Bo2loz/bo2loz_venv/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "RobEn.py", line 70, in on_message
    if message.author.bot or message.channel.id != message.author.dm_channel.id:
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by mhwahdan** [comment]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\moust\.conda\envs\robben_discord_bot\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "e:\Git Repositories\Discord-bot\RobEn.py", line 76, in on_message
    channel = await message.author.create_dm()
AttributeError: 'ClientUser' object has no attribute 'create_dm'
